---
  TRADE_OPTIONS:
    # In your pairing coin
    QUANTITY: 15
    # BTCUSDT will be bought for example
    PAIRING: USDT
    # How often to check for posts and run the script
    # in minutes
    RUN_EVERY: 0.025
    TEST: True
    # In %
    SL: -3
    TP: 2
    ENABLE_TSL: True
    TSL: -4
    TTP: 2
  LOGGING:
    # Logging levels used in this program are ERROR, INFO, and DEBUG
    LOG_LEVEL: INFO
    LOG_FILE: bot.log